### ISSUE TITLE
Typescritp error after upgrading to 4.3.0

### ISSUE THREAD

**Issue by carloscortonc** [tstyche/tstyche#585]
The error I am getting is: https://github.com/carloscortonc/cli-er/actions/runs/17402416557/job/49398408512?pr=98#step:6:7

```sh
Error: node_modules/tstyche/build/index.d.ts(103,48): error TS2304: Cannot find name 'DecoratorContext'.
```

After some digging, I found out this was introduced in v4.0.0 [here](https://github.com/tstyche/tstyche/pull/447/files)

https://github.com/tstyche/tstyche/blob/2039388bba7f19b3157b06735314604f3d06c83b/source/types.ts#L105

From what I could read, this type was introduced in typescript 5.0, but tstyche documentation states that only version `>=4.7` is required (https://tstyche.org/guides/typescript-versions#supported-versions)

**Comment by mrazauskas** [comment]
Hm.. If I did not mix up anything, origin of the error is `tsc`.

But the problem is Node.js support:

- TSTyche 4 requires at least Node.js `20.9`;
- TSTyche 3 requires at least Node.js `18.19`.

From what I see the highest version of Node.js you are using in CI is currently `16`. Do you plan to upgrade? If not, your best bet is TSTyche 2 with the minimum required Node.js `16.14`. Seems like TSTyche 2 ([release notes](https://tstyche.org/releases/tstyche-2)) would cover the needs of your project. Could this be the best solution for all compatibility issues, perhaps?

**Comment by carloscortonc** [comment]
Same result: https://github.com/carloscortonc/cli-er/actions/runs/17403326567/job/49401397919

**Comment by mrazauskas** [comment]
Ah.. Can I ask why you keep old TypeScript version? TSTyche does not need it. You can run `tstyche --target 4.7` test against older TS version. Or event `tstyche --target '>=4.7'` to test agains a range of versions.

Perhaps it is time to upgrade TypeScript? Might be you have a reason to keep older version. Let me think...

**Comment by carloscortonc** [comment]
Yeah I should probably consider upgrading typescript... I just thought it was strange that this happened, considering I am inside required typescript version, thats all.

Thank you anyways for your time!

**Comment by mrazauskas** [comment]
Or, I should try to use the [`typesVersions`](https://typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions) field and provide different `.d.ts` for TypeScript `<5.0`.
